name: ci-golang-workflow
on:
  push:
    branches:
      - 'develop'

jobs:
  check-aplication:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
